# Generated by Django 4.1.3 on 2022-12-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TGId', models.CharField(max_length=255)),
                ('Order_id', models.CharField(max_length=255)),
                ('Platform', models.CharField(max_length=255)),
                ('Displayed_id', models.CharField(blank=True, max_length=255)),
                ('Current_state', models.CharField(blank=True, max_length=255)),
                ('Cart', models.TextField()),
                ('Store_id', models.IntegerField()),
                ('Placed_at', models.DateTimeField(blank=True)),
            ],
        ),
    ]
