# Generated by Django 4.1.3 on 2023-04-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Current_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Store_id',
        ),
        migrations.AddField(
            model_name='order',
            name='Branch_Id',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='Merch_Id',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='Price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Cart',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Displayed_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
