# Generated by Django 4.1.3 on 2022-12-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchID', models.CharField(max_length=255)),
                ('BranchID', models.CharField(max_length=255)),
                ('ValidUntil', models.DateTimeField()),
                ('Channel', models.IntegerField()),
                ('HungryPanda', models.BooleanField()),
                ('Deliveroo', models.BooleanField()),
                ('UberEats', models.BooleanField()),
                ('Fantuan', models.BooleanField()),
            ],
        ),
    ]
