# Generated by Django 4.1.3 on 2022-12-21 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Validate',
        ),
    ]
