# Generated by Django 4.1.3 on 2023-04-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0002_rename_order_validate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validate',
            name='Channel',
        ),
        migrations.AddField(
            model_name='validate',
            name='DR_Valid',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='validate',
            name='FT_Valid',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='validate',
            name='HP_Valid',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='validate',
            name='UE_Valid',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='validate',
            name='ValidUntil',
            field=models.DateField(),
        ),
    ]
